modLoader="javafml"
loaderVersion="[46,)"
license="LGPLv3"
issueTrackerURL="https://github.com/xfacthd/packetlogger"

[[mods]]
	modId="packetlogger"
	version="${file.jarVersion}"
	displayName="PacketLogger"
	#updateJSONURL="https://change.me.example.invalid/updates.json"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/packetlogger"
	logoFile="logo.png"
	authors="XFactHD"
	displayTest="IGNORE_ALL_VERSION"
	description='''
	'''

[[dependencies.packetlogger]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.packetlogger]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
