modLoader="javafml"
loaderVersion="${loader_version_range}"
license="LGPLv3"
issueTrackerURL="https://github.com/xfacthd/packetlogger"

[[mods]]
	modId="packetlogger"
	version="${mod_version}"
	displayName="PacketLogger"
	#displayURL="https://www.curseforge.com/minecraft/mc-mods/packetlogger"
	logoFile="logo.png"
	authors="XFactHD"
	displayTest="IGNORE_ALL_VERSION"
	description='''
	'''

[[mixins]]
    config="packetlogger.mixin.json"

[[dependencies.packetlogger]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.packetlogger]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
